#### Takes a fitted lavaan model, and a list of coefficients, and returns the estimates, SEs,
# z-scores, and p-values.
# fit: the model that results from a call to lavaan::sem() or lavaan::cfa()
# coefs: a pair (or list of pairs) of model components for which you want
#        a summary of the coefficients/covariances.
# tails: whether p-values should represent 1- or 2-tailed tests.
# *.digits: how many significant digits you want displayed for each component
#           of the output. (sig.digits will provide a default value)

extract.coef=function(fit, coefs, sig.digits = 3, tails = 2, est.digits = sig.digits
                      , se.digits = sig.digits, z.digits = sig.digits
                      , p.digits = sig.digits) {
  ### Takes an sem object, and a list of "variable" pairs (could be latent observed)
  # and returns the coefficient(s) from fit
  # It can also take a lavaan.data.frame (as generated by standardizedSolution())
  # sig.digits will be used for rounding (so it's sort of misnamed) and applies to all
  # values in the table, unless overridden by one of the *.digits options
  # tails can be either 1 or 2, and indicates whether p-values reflect one or two-tailed 
  # tests
  
  if(!tails %in% 1:2) warning(paste0("Can not conduct a ", tails, "-tailed test."))
  
  if(class(fit)[1]=="lavaan"){
    fit = data.frame(fit@ParTable)
  } 
  
  if(!any(class(fit)=="data.frame")) {
    warning(paste0("fit must be either class 'lavaan' or inherit 'data.frame'. "
                   , "Coerce to data.frame before calling extract.coef."))
    return(NULL)
  }
  
  coefLbls1 = paste0(fit$rhs, "*op*", fit$lhs)
  coefLbls2 = paste0(fit$lhs, "*op*", fit$rhs)
  
  if(is.list(coefs)) {
    return(lapply(coefs, extract.coef, fit = fit, sig.digits = sig.digits
                  , est.digits = est.digits, se.digits = se.digits, z.digits = z.digits
                  , p.digits = p.digits) %>% bind_rows)
  }
  if(!is.list(coefs) & length(coefs)==2){
    fndstr = paste0(coefs[1], "*op*", coefs[2])
    rhs = fit$rhs[coefLbls1==fndstr | coefLbls2==fndstr]
    lhs = fit$lhs[coefLbls1==fndstr | coefLbls2==fndstr]
    op = fit$op[coefLbls1==fndstr | coefLbls2==fndstr]
    mtchest = fit$est[coefLbls1==fndstr | coefLbls2==fndstr]
    mtchse = fit$se[coefLbls1==fndstr | coefLbls2==fndstr]
    rtrn=data.frame(Param=paste(lhs, op, rhs), Est = mtchest, SE=mtchse
                    , stringsAsFactors = F)
    rtrn$z_val = rtrn$Est/rtrn$SE
    rtrn$p = round((1-pnorm(abs(rtrn$z_val)))*ifelse(tails==1,1,ifelse(tails==2,2,NA))
                   , p.digits)
    rtrn$z_val = round(rtrn$z_val, z.digits)
    rtrn$Est = round(rtrn$Est, est.digits)
    rtrn$SE = round(rtrn$SE, se.digits)
    if(!nrow(rtrn)) {
      warning(
        paste0("Unable to find a connection from ", coefs[1], " to ", coefs[2]
               , ". Check the model specification and coefs parameter.")
      )
      rtrn[1,]=c(paste(coefs[1], "??", coefs[2]),rep(NA, ncol(rtrn)-1))
    }
    return(rtrn)
  } else {
    warning("coef must be either a vector of length 2, or a list of vectors of length 2, 
            (or a list of lists of vectors...)")
  }
}

### Example usage (just using the PoliticalDemocracy dataset from the "sem" 
# help example)

model <- ' 
  # latent variable definitions
     ind60 =~ x1 + x2 + x3
     dem60 =~ y1 + a*y2 + b*y3 + c*y4
     dem65 =~ y5 + a*y6 + b*y7 + c*y8

  # regressions
    dem60 ~ ind60
    dem65 ~ ind60 + dem60

  # residual correlations
    y1 ~~ y5
    y2 ~~ y4 + y6
    y3 ~~ y7
    y4 ~~ y8
    y6 ~~ y8
'

PD.fit <- sem(model, data = PoliticalDemocracy)

# For a single coefficient:
extract.coef(PD.fit, c("dem60", "ind60"), sig.digits=4)

# For a group of coefficients, using one-tailed tests, with more digits for p:
coefsList=list(c("dem60", "ind60"), c("dem65", "ind60"), c("dem60", "dem65"))
extract.coef(PD.fit, coefsList, tails=1, p.digits=4)

