# Gaussian analysis of Binomial Data.

# I have a question about what happens when you take values generated by a binomial model
# and analyze it as though it were normal.

# I'm just wondering what the Type I error rate would be.
include(dplyr)

# Let's just do a quick demo for the example data:
NTrials = 38
TrueP = 10/38

# The model is cbind(NCorrect, 38)~x, where x is N(0,1).
N = 875
dat = data.frame(NTrials = NTrials, x=rnorm(N)) %>% 
  mutate(p = .97*TrueP+.03*exp(x)/(1+exp(x)))

p.nrml = p.lgstc = numeric(10000)

strt = Sys.time()
for (i in 1:length(p.nrml)){
  dat$NCorrect = rbinom(N, NTrials, dat$p)
  p.nrml[i]=summary(lm(NCorrect~x, dat))$coeff[2,4]
  p.lgstc[i]=summary(glm(cbind(NCorrect, NTrials)~x, dat, family=binomial))$coeff[2,4]
  if(!i%%100) message(paste(i, Sys.time()-strt))
}

mean(p.nrml<=.05); mean(p.lgstc<=.05)
